# Generated by Django 4.2.1 on 2023-06-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_tag_alter_post_created_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='000000FF', max_length=8),
        ),
    ]
