name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DJANGO_DEBUG: 0
  DJANGO_SECRET_KEY: 03je90h90erh28h18hef8hwsdhfohs0adfjh-sadf7asd7
  PG_USER: pguser
  PG_PASSWORD: pgpassword
  PG_NAME: board
  PG_HOST: 127.0.0.1
  PG_PORT: 5432
  REDIS_HOST: 127.0.0.1
  REDIS_PORT: 6379
  JWT_SIGNING_KEY: 03je90h90erh28h18hef8hwsdhfohs0adfjh-sadf7asd7
  DOCKERHUB_IMAGE_NAME: board

jobs:


  test:

    runs-on: ubuntu-latest

    services:
      database:
        image: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpassword
          POSTGRES_DB: board
    
      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run manage.py test

    - name: Upload coverage result
      uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}

  build_docker_image:
    needs:
      - test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}:latest
